MaxTrautwein/AStA-Digital-Forms

Doc/main.tex
Doc/paragraphs/Aufwandsschaetzung.tex
Doc/paragraphs/Funktionsumfang.tex

Draft to Tack Documentation Progress

Funktionsumfang & Aufwandsschätzung

---

Doc/bib/online.bib
Doc/main.tex
Doc/paragraphs/Lizenzen.tex
Doc/paragraphs/Techno.tex

Technology Description

---

Doc/main.tex
Doc/paragraphs/Architekturschichten.tex

Ein Anfang ist gemacht, der Rest kommt mit der Implementierung

Architekturschichten angelegt und in main.tex integriert. 

---

Doc/main.tex
Doc/paragraphs/API.tex
Doc/paragraphs/Lizenzen.tex
Doc/paragraphs/Mockups.tex
Doc/paragraphs/Techno.tex
Doc/paragraphs/Userstories.tex

Issue45 (doku fixes)

---

.github/workflows/Deploy.yml
Deploy.patch

`Deploy.patch` is used with https://gist.github.com/MaxTrautwein/59dcb203f85922b0fb344470b36d0a3f to deploy the app.
`.github/workflows/Deploy.yml` Unfortunately, can't be tested until it is on Master. It should trigger that Deployment Automatically

#33 Added Support for Automatic Deplyment

---

Deploy.patch

Noticed the production environment going down, 
added `restart: unless-stopped` to prevent that

#33 updated Deploy.patch to prevent unintended restarts

---

Backend/src/main/java/de/PSWTM/DigitalForms/WebConfig.java
Backend/src/main/resources/application.properties
Backend/src/main/resources/openapi.yaml

#67 prevented CORS Errors by allowing the relevant origins

---

Frontend/src/app/app.component.html
Frontend/src/app/main-buttons/main-buttons.component.css
Frontend/src/app/main-buttons/main-buttons.component.html
Frontend/src/app/main-buttons/main-buttons.component.ts

Page loads dynamical after login (and potentialy a reload of the side). Also issues concerning the buttons on rezizing the window is fixed as good as possible. Bitte Änderungswünsche mitteilen

Issue65 dynamic landing page

---

Frontend/src/app/app.component.html
Frontend/src/app/app.component.ts
Frontend/src/app/app.routes.ts
Frontend/src/app/app.service.ts
Frontend/src/app/auth.config.ts
Frontend/src/app/dashboard/dashboard.component.html
Frontend/src/app/dashboard/dashboard.component.spec.ts
Frontend/src/app/dashboard/dashboard.component.ts
Frontend/src/app/form-container/form-container.component.html
Frontend/src/app/form-container/form-container.component.spec.ts
Frontend/src/app/form-container/form-container.component.ts
Frontend/src/app/form-container/form-content/form-content.component.html
Frontend/src/app/form-container/form-content/form-content.component.spec.ts
Frontend/src/app/form-container/form-content/form-content.component.ts
Frontend/src/app/form-container/form-content/text/text.component.html
Frontend/src/app/form-container/form-content/text/text.component.spec.ts
Frontend/src/app/form-container/form-content/text/text.component.ts
Frontend/src/app/form-container/progress-controls/progress-contolls.component.html
Frontend/src/app/form-container/progress-controls/progress-contolls.component.spec.ts
Frontend/src/app/form-container/progress-controls/progress-contolls.component.ts
Frontend/src/app/form-container/progress-display/progress-display.component.css
Frontend/src/app/form-container/progress-display/progress-display.component.html
Frontend/src/app/form-container/progress-display/progress-display.component.spec.ts
Frontend/src/app/form-container/progress-display/progress-display.component.ts
Frontend/src/app/main-buttons/main-buttons.component.html
Frontend/src/app/main-buttons/main-buttons.component.ts
Frontend/src/app/nav-bar/nav-bar.component.html
Frontend/src/app/nav-bar/nav-bar.component.ts
Frontend/src/app/template.service.ts
Frontend/src/app/templete.service.spec.ts

Barebones Form

---

Backend/pom.xml
Backend/src/main/resources/application-test.properties
Backend/src/test/java/de/PSWTM/DigitalForms/DigitalFormsApplicationTests.java

Fixed Tests by adding Embedded DB
Spent 45 Minutes Researching and Implementing

Added Embedded MongoDB to allow tests to run in compose build

---

Frontend/src/app/collapsable-bottom/collapsable-bottom.component.html
Frontend/src/app/collapsable-bottom/collapsable-bottom.component.ts
Frontend/src/app/collapsable-bottom/marked-item/marked-item.component.html
Frontend/src/app/collapsable-bottom/marked-item/marked-item.component.spec.ts
Frontend/src/app/collapsable-bottom/marked-item/marked-item.component.ts
Frontend/src/app/form-container/form-container.component.ts
Frontend/src/app/form-container/form-content/form-content.component.html
Frontend/src/app/form-container/form-content/text/text.component.html
Frontend/src/app/form-container/form-content/text/text.component.ts

Frontend Loading

---

Backend/src/main/java/de/PSWTM/DigitalForms/configuration/DatabaseLoader.java
Backend/src/main/java/de/PSWTM/DigitalForms/repository/FormRepository.java
Frontend/src/app/main-buttons/main-buttons.component.css
Frontend/src/app/main-buttons/main-buttons.component.html
Frontend/src/app/main-buttons/main-buttons.component.ts
Frontend/src/app/template.service.ts

Musste im Prozess umplanen, weil ich gemerkt habe, dass es unmöglich ist, jedem Antrag auch eine Abrechnung zuzuteilen. Habe die Getter für Anträge bzw. Abrechnungen mal noch im Templateservice gelassen, falls wir sie später mal gebrauchen können. Wenn ihr wollt, können die aber auch wieder raus.

Issue90 main page selection

---

Frontend/src/app/app-routing.module.ts
Frontend/src/app/app.component.ts
Frontend/src/app/app.config.ts
Frontend/src/app/app.routes.ts
Frontend/src/app/app.service.ts
Frontend/src/app/auth.config.ts
Frontend/src/app/collapsable-bottom/collapsable-bottom.component.html
Frontend/src/app/collapsable-bottom/collapsable-bottom.component.ts
Frontend/src/app/collapsable-bottom/marked-item/marked-item.component.ts
Frontend/src/app/dashboard/dashboard.component.ts
Frontend/src/app/form-container/form-content/text/text.component.ts
Frontend/src/app/form-container/progress-display/progress-display.component.spec.ts
Frontend/src/app/main-buttons/main-buttons.component.css
Frontend/src/app/main-buttons/main-buttons.component.html
Frontend/src/app/nav-bar/nav-bar.component.ts
Frontend/src/app/prepare-api.service.ts
Frontend/src/app/template.service.ts

I have tested it, only changed things in the frontend and it is still running and functioning normal! But of course you can test it ^^

my personal code cleanup

---

Frontend/src/app/user-data/user-data.component.css
Frontend/src/app/user-data/user-data.component.html

Issue117 autofill page

---

Backend/src/main/java/de/PSWTM/DigitalForms/Services/PdfService.java
Backend/src/main/java/de/PSWTM/DigitalForms/configuration/DatabaseLoader.java
Backend/src/main/resources/templates/AbrechnungeinesVorschusses.html
Backend/src/main/resources/templates/AbrechnungvonFachschaftswochenenden.html
Backend/src/main/resources/templates/AntragAufGenehmigenTemplate.html
Backend/src/main/resources/templates/ErstattungvonAuslagenundRechnungen.html
Backend/src/main/resources/templates/ErstattungvonReisekosten.html
Backend/src/main/resources/templates/GenehmigungvonFachschaftswochenenden.html
Backend/src/main/resources/templates/GenehmigungvonReisen.html
Backend/src/main/resources/templates/GenehmigungvonReisenmitFahrgemeinschaften.html
Backend/src/main/resources/templates/GenehmigungvonkulturellenVeranstaltungen.html
Backend/src/main/resources/templates/GenehmigungvonwirtschaftlichenVeranstaltungen.html
README.md

resolves #39
We need to implement some things first before we can document them...
Doc is in the Wiki

Admin Guide & Co

---

Frontend/src/app/login/login.component.css

Resize Login Page mit AStA-Orange hover

---

Frontend/src/app/nav-bar/nav-bar.component.css
Frontend/src/app/nav-bar/nav-bar.component.html
Frontend/src/app/nav-bar/nav-bar.component.ts

Made Navbar scalable as good as possible, hide unneeded nav elements before login, Account name is now customized

Issue115 navbar update

---

Backend/src/main/java/de/PSWTM/DigitalForms/Services/PdfService.java

Fixes error where PDF generation fails on an incomplete Form due to null Values
Spent 16 min on the fix and testing

fixed error with pdf gen on incomplete form

---

Doc/main.tex
Doc/paragraphs/ReflektionLernfortschritt.tex
Doc/paragraphs/ReflektionProjektmanagement.tex

Added initial pages for reflekting

---

Doc/main.tex
Doc/paragraphs/Ausblick.tex
Doc/paragraphs/Mockups.tex

Issue 35 ausblick

---

Frontend/src/app/form-container/form-container.component.css
Frontend/src/app/form-container/form-container.component.html
Frontend/src/app/form-container/form-content/address/address.component.css
Frontend/src/app/form-container/form-content/bool/bool.component.css
Frontend/src/app/form-container/form-content/date/date.component.css
Frontend/src/app/form-container/form-content/iban/iban.component.css
Frontend/src/app/form-container/form-content/money/money.component.css
Frontend/src/app/form-container/form-content/text-multi-line/text-multi-line.component.css
Frontend/src/app/form-container/form-content/text/text.component.css

resolve scroll issue without changing bootstrap

---

Doc/paragraphs/ReflektionLernfortschritt.tex
Doc/paragraphs/ReflektionProjektmanagement.tex

reflektion Max

---

Doc/paragraphs/ReflektionProjektmanagement.tex

Reflektion PM von Ayhan

---

Doc/paragraphs/Datenbank.tex

Updated the Database Doc

---

Doc/paragraphs/ReflektionLernfortschritt.tex

Lernfortschritt Ayhan
